# Generated by Django 4.1.7 on 2023-03-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghApp', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='accountUsername',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ghApp.account'),
        ),
    ]
