# Generated by Django 4.1.7 on 2023-03-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghApp', '0003_userdetails_accountusername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userDetails',
            new_name='userInfo',
        ),
    ]
